version: '3'
services:
  web:
    container_name: roastia
    image: hegelocampus/roastia
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
